### ISSUE TITLE
Zorg dat text zichtbaar blijft wanneer een font wordt ingeladen

### ISSUE THREAD

**Issue by Amberhva** [r20222/performance-matters-optimized-website#28]
Dit kan je zo doen

```css
@font-face {
  font-family: 'Pacifico';
  font-style: normal;
  font-weight: 400;
  src: local('Pacifico Regular'), local('Pacifico-Regular'),
    url(https://fonts.gstatic.com/s/pacifico/v12/FwZY7-Qmy14u9lezJ-6H6MmBp0u-.woff2)
      format('woff2');
  font-display: swap;
}
```
